# Generated by Django 4.0.6 on 2022-07-19 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thornsNRosesAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThornUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_employee', models.BooleanField()),
                ('nursery_employee', models.BooleanField()),
                ('retail_employee', models.BooleanField()),
                ('event_planner', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
